//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfomatSelfChecking.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfomatSelfChecking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработка приложения:
        ///ООО &quot;Клиника ЛМС&quot;
        ///dev@bzklinika.ru.
        /// </summary>
        public static string about_developer {
            get {
                return ResourceManager.GetString("about_developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметка о посещении успешно проставлена
        ///
        ///Пожалуйста пройдите на приём.
        /// </summary>
        public static string appointments_mark_ok {
            get {
                return ResourceManager.GetString("appointments_mark_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для отметки о посещении
        ///просьба пройти в регистратуру.
        /// </summary>
        public static string appointments_mark_problem {
            get {
                return ResourceManager.GetString("appointments_mark_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список записей успешно распечатан.
        /// </summary>
        public static string appointments_print_ok {
            get {
                return ResourceManager.GetString("appointments_print_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, по техническим причинам
        ///не удалось распечатать список записей
        ///Информация о проблеме будет передана
        ///ответственным лицам.
        /// </summary>
        public static string appointments_print_problem {
            get {
                return ResourceManager.GetString("appointments_print_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имеются записи, запланированные за наличный расчет
        ///Необходимо заранее оплатить данные приёмы.
        /// </summary>
        public static string appointments_warning_cash {
            get {
                return ResourceManager.GetString("appointments_warning_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для отметки о посещении необходимо обратиться в регистратуру.
        /// </summary>
        public static string appointments_warning_general {
            get {
                return ResourceManager.GetString("appointments_warning_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имеются записи с пропущенным временем начала
        ///Необходимо согласовать перенос на другое время.
        /// </summary>
        public static string appointments_warning_time {
            get {
                return ResourceManager.GetString("appointments_warning_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имеются записи в рентгенологическое отделение.
        /// </summary>
        public static string appointments_warning_xray {
            get {
                return ResourceManager.GetString("appointments_warning_xray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению,
        ///cервис временно недоступен
        ///
        ///Попробуйте позднее
        ///или обратитесь в регистратуру.
        /// </summary>
        public static string notification_db_not_available {
            get {
                return ResourceManager.GetString("notification_db_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы впервые в нашей клинике,
        ///
        ///Пожалуйста, пройдите в регистратуру
        ///для оформления необходимых документов.
        /// </summary>
        public static string notification_first_visit {
            get {
                return ResourceManager.GetString("notification_first_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для отметки о посещении
        ///Вам необходимо обратиться в регистратуру.
        /// </summary>
        public static string notification_need_go_to_registry {
            get {
                return ResourceManager.GetString("notification_need_go_to_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На ближайшее время у Вас нет записей
        ///
        ///За подробной информацией Вы можете
        ///обратиться в регистратуру.
        /// </summary>
        public static string notification_no_appointmetns_for_now {
            get {
                return ResourceManager.GetString("notification_no_appointmetns_for_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, по номеру *
        ///не найдено записей на сегодня
        ///
        ///Возможно указан неверный номер
        ///Попробуйте снова или обратитесь в регистратуру.
        /// </summary>
        public static string notification_nothing_found {
            get {
                return ResourceManager.GetString("notification_nothing_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продолжения коснитесь экрана.
        /// </summary>
        public static string notification_tap_to_continue {
            get {
                return ResourceManager.GetString("notification_tap_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обслуживаетесь по страховке?
        ///Здесь можно отметиться на приём!.
        /// </summary>
        public static string notification_welcome {
            get {
                return ResourceManager.GetString("notification_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможно введен неправильный номер телефона
        ///
        ///Попробуйте снова
        ///или обратитесь в регистратуру.
        /// </summary>
        public static string notification_wrong_name {
            get {
                return ResourceManager.GetString("notification_wrong_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У Вас имеются записи за наличный расчет
        ///Просьба пройти в регистратуру для оплаты приёма.
        /// </summary>
        public static string print_message_final_cash {
            get {
                return ResourceManager.GetString("print_message_final_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для отметки о посещении
        ///Просьба пройти в регистратуру.
        /// </summary>
        public static string print_message_final_multiple {
            get {
                return ResourceManager.GetString("print_message_final_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просьба проходить на приём.
        /// </summary>
        public static string print_message_final_ok {
            get {
                return ResourceManager.GetString("print_message_final_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У Вас имеются записи, у которых пропущено время начала
        ///Просьба пройти в регистратуру для согласования переноса.
        /// </summary>
        public static string print_message_final_time {
            get {
                return ResourceManager.GetString("print_message_final_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У Вас имеются записи в рентгенологическое отделение
        ///Просьба пройти в регистратуру для отметки о посещении.
        /// </summary>
        public static string print_message_final_xray {
            get {
                return ResourceManager.GetString("print_message_final_xray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, оцените качество
        ///приёма у врача,
        ///воспользовавшись терминалом,
        ///установленным в холле клиники
        ///
        ///Ваше мнение
        ///очень важно для нас!.
        /// </summary>
        public static string print_message_information_loyalty {
            get {
                return ResourceManager.GetString("print_message_information_loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В нашей клинике
        ///доступен новый сервис:
        ///«Личный кабинет пациента»
        ///
        ///Получить логин и пароль
        ///Вы можете при предъявлении
        ///паспорта в регистратуре.
        /// </summary>
        public static string print_message_information_private_office {
            get {
                return ResourceManager.GetString("print_message_information_private_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От начала ближайшего приёма прошло минут: @minutes.
        /// </summary>
        public static string print_message_time_late {
            get {
                return ResourceManager.GetString("print_message_time_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До начала ближайшего приёма осталось минут: @minutes.
        /// </summary>
        public static string print_message_time_ok {
            get {
                return ResourceManager.GetString("print_message_time_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием запланирован за наличный расчет.
        /// </summary>
        public static string print_notification_cash {
            get {
                return ResourceManager.GetString("print_notification_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропущено время начала приёма.
        /// </summary>
        public static string print_notification_time {
            get {
                return ResourceManager.GetString("print_notification_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string print_notification_xray {
            get {
                return ResourceManager.GetString("print_notification_xray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - наличный расчет.
        /// </summary>
        public static string show_appointments_cash {
            get {
                return ResourceManager.GetString("show_appointments_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - пропущено время.
        /// </summary>
        public static string show_appointments_late {
            get {
                return ResourceManager.GetString("show_appointments_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - лучевая диагностика.
        /// </summary>
        public static string show_appointments_roentgen {
            get {
                return ResourceManager.GetString("show_appointments_roentgen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имеются записи, по которым Вам нужно обратиться в регистратуру:.
        /// </summary>
        public static string show_appointments_warning {
            get {
                return ResourceManager.GetString("show_appointments_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *,
        ///Ваши записи на ближайшее время:.
        /// </summary>
        public static string title_appointments {
            get {
                return ResourceManager.GetString("title_appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для отметки о посещении
        ///введите Ваш номер мобильного телефона.
        /// </summary>
        public static string title_dialer {
            get {
                return ResourceManager.GetString("title_dialer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста,
        ///убедитесь в соответствии Ваших данных:.
        /// </summary>
        public static string title_name_confirm {
            get {
                return ResourceManager.GetString("title_name_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите пациента из списка:.
        /// </summary>
        public static string title_name_confirm_multiple {
            get {
                return ResourceManager.GetString("title_name_confirm_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемый пациент!.
        /// </summary>
        public static string title_notification {
            get {
                return ResourceManager.GetString("title_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважаемые пациенты!.
        /// </summary>
        public static string title_welcome {
            get {
                return ResourceManager.GetString("title_welcome", resourceCulture);
            }
        }
    }
}
